import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// TODO: Substituir as variáveis de ambiente do Vite pelas do Next.js
// Next.js usa process.env.NEXT_PUBLIC_VARIAVEL
export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_APP_TITLE || "Next.js Mock Project",
  description: "Generated by Next.js", // Adicionar uma descrição adequada
};

import AppProvider from "./App";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Favicon e Apple Touch Icon - Next.js usa o diretório public/ para assets estáticos */}
        {/* O Next.js tem um sistema de metadados integrado, mas podemos manter a tag link para compatibilidade */}
        <link rel="icon" type="image/png" href={process.env.NEXT_PUBLIC_APP_LOGO || "/favicon.ico"} />
        <link rel="apple-touch-icon" href={process.env.NEXT_PUBLIC_APP_LOGO || "/apple-touch-icon.png"} />
        
        {/* Google Fonts (exemplo) */}
        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" /> */}
      </head>
      <body className={inter.className}>
        <AppProvider>
          {children}
        </AppProvider>
        {/* Script de Analytics (Umami) - Adaptado para Next.js */}
        {process.env.NEXT_PUBLIC_ANALYTICS_ENDPOINT && process.env.NEXT_PUBLIC_ANALYTICS_WEBSITE_ID && (
          <script
            defer
            src={`${process.env.NEXT_PUBLIC_ANALYTICS_ENDPOINT}/umami`}
            data-website-id={process.env.NEXT_PUBLIC_ANALYTICS_WEBSITE_ID}
          ></script>
        )}
      </body>
    </html>
  );
}
